global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'blockchain-anomaly-detection'

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Rule files (optional)
rule_files:
  # - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Blockchain Anomaly Detection API
  - job_name: 'blockchain-api'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['api:8000']
        labels:
          service: 'blockchain-api'
          environment: 'development'

  # Additional API metrics endpoint
  - job_name: 'blockchain-api-metrics'
    metrics_path: '/api/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['api:8000']
        labels:
          service: 'blockchain-api'
          environment: 'development'
