apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anomaly-detection-models-pvc
  namespace: blockchain-anomaly-detection
  labels:
    app: anomaly-detection
spec:
  accessModes:
    - ReadOnlyMany  # Multiple pods can read
  storageClassName: standard  # Adjust based on your cluster
  resources:
    requests:
      storage: 5Gi

---
# If using NFS or other shared storage, define PV
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: anomaly-detection-models-pv
#   labels:
#     app: anomaly-detection
# spec:
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadOnlyMany
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: standard
#   nfs:
#     server: nfs-server.example.com
#     path: /path/to/models
